name: Docker Image CI

on:
  push:
    branches: [ "dockerfile" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag devcontainer_image:$(date +%s)
